language: android
jdk: oraclejdk8
android:
components:
- tools
- platform-tools
- build-tools-25.0.3
- android-25
- sys-img-armeabi-v7a-android-22
- sys-img-armeabi-v7a-android-17
- extra-android-m2repository
- sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
before_install:
- chmod +x gradlew

before_script:
- chmod +x ./gradlew

#script:
#./gradlew jacocoTestReport


after_success:
- bash <(curl -s https://codecov.io/bash)