language: android
jdk:
  - oraclejdk8
  env:
    matrix:
      - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
android:
  components:
      - tools
      - platform-tools
      - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-17
    - extra-android-support

licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
script:
      - ./gradlew build
      - ./gradlew build jacocoTestReport assembleAndroidTest