language: android
jdk: oraclejdk8
android:
components:

- build-tools-25.0.3

- android-25

- sys-img-armeabi-v7a-android-22
- sys-img-armeabi-v7a-android-17

before_install:
- chmod +x gradlew

before_script:
  - chmod +x ./gradlew
script:
- ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
- bash <(curl -s https://codecov.io/bash)