language: android
jdk:
  - oraclejdk8
  env:
    matrix:
      - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
android:
  components:
      - tools
      - platform-tools
      - tools
    - build-tools-25.0.3
    - android-25

    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17

      licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'